<?=$this->view('jqgrid')->set('config', array(
    'grid' => array(
        'id' => 'product_vendors',
        'caption' => 'Product Vendors',
        'url' => BApp::url('Denteva_Admin', '/products/'.$this->model->id.'/vendors/grid_data'),
        'columns' => array(
            'id'=>array('name'=>'id', 'label'=>'ID', 'width'=>50, 'hidden'=>true),
            'vendor_code'=>array('label'=>'Vendor', 'width'=>100),
            'vendor_sku'=>array('label'=>'Vendor SKU', 'width'=>100),
            'manuf_name'=>array('label'=>'Manuf Name', 'width'=>100),
            'manuf_sku'=>array('label'=>'Mfr Part #', 'width'=>100),
            'manuf_sku_clean'=>array('label'=>'Clean Part # ', 'width'=>100),
            'description'=>array('label'=>'Name', 'width'=>100),
            'description'=>array('label'=>'Description', 'width'=>100),
            //'family_name'=>array('label'=>'Family', 'width'=>100),
            'cost'=>array('label'=>'Cost', 'width'=>100),
            'uom'=>array('label'=>'UOM', 'width'=>100),
            'category'=>array('label'=>'Category', 'width'=>100),
            'manuf_url'=>array('label'=>'Manuf URL', 'width'=>100),
            'vendor_url'=>array('label'=>'Vendor URL', 'width'=>100),
            'image_url'=>array('label'=>'Image URL', 'width'=>100),
            'thumb_url'=>array('label'=>'Thumb URL', 'width'=>100),
            'manuf_match_type'=>array('label'=>'Mfr Match Type', 'width'=>100),
        ),
        'multiselect' => true,
    ),
    'custom'=>array('personalize'=>true),
    'navGrid' => array('add'=>false, 'edit'=>false, 'search'=>false, 'del'=>false, 'refresh'=>false),
    array('navButtonAdd', 'caption' => 'Add', 'buttonicon'=>'ui-icon-plus', 'title' => 'Add Vendor', 'cursor'=>'pointer'),
    array('navButtonAdd', 'caption' => 'Remove', 'buttonicon'=>'ui-icon-trash', 'title' => 'Remove Vendor', 'cursor'=>'pointer'),
)) ?>