modules:
    FCom_Core:
        version: 0.6.1.0
        channel: beta
        before_bootstrap: { callback: "FCom_Core_Main::onBeforeBootstrap" }
        run_level: REQUIRED
        description: "Base Sellvana classes and JS libraries"
        load_after: [ FCom_LibTwig ]
        auto_use: [ layout, views ]
        override:
            class:
                - [ BDbModule, FCom_Core_Model_Module ]
        views:
            - [ head, { view_class: FCom_Core_View_Head } ]
            - [ head_script, { view_class: FCom_Core_View_Text } ]
            - [ head_css, { view_class: FCom_Core_View_Text } ]
            - [ core/messages, { view_class: FCom_Core_View_Messages } ]
            - [ bottom_scripts, { view_class: FCom_Core_View_Head } ]
            - [ core/htmlgrid, { view_class: FCom_Core_View_HtmlGrid } ]
            - [ core/form-elements, { view_class: FCom_Core_View_FormElements } ]
            - [ core/backgrid, { view_class: FCom_Core_View_Backgrid } ]
            - [ core/slickgrid, { view_class: FCom_Core_View_Slickgrid } ]
            - [ core/simplegrid, { view_class: FCom_Core_View_SimpleGrid } ]
            - [ core/backbonegrid, { view_class: FCom_Core_View_BackboneGrid } ]
            - [ core/griddle, { view_class: FCom_Core_View_BackboneGrid } ]
            - [ core/medialib, { view_class: FCom_Core_View_Base } ]
            - [ core/medialib-griddle, { view_class: FCom_Core_View_Base } ]
            - [ core/attachmentgrid, { view_class: FCom_Core_View_Base } ]
            - [ text, { view_class: FCom_Core_View_Text } ]

        routing:
            - [ /initialize.js, FCom_Core_Controller_Main.initialize_js ]
            - [ /initialize.css, FCom_Core_Controller_Main.initialize_css ]

        observe:
            - [ "FCom_LibTwig_Main::init", FCom_Core_Main.onTwigInit ]
            - [ "FCom_Core_LayoutEditor::fetchLibrary", "FCom_Core_LayoutEditor.onFetchLibrary" ]
            - [ "BORM::find_one:after", FCom_Core_Main.onFindOneAfter ]
            - [ "BORM::find_many:after", FCom_Core_Main.onFindManyAfter ]
            - [ "FCom_Core_ImportExport::import:afterModel:FCom_Core_Model_ExternalConfig", "FCom_Core_Main.onConfigAfterCoreImport" ]

        areas:
            FCom_Shell:
                custom:
                    actions:
                        - FCom_Core_Shell_Cache
                        - FCom_Core_Shell_Config
                        - FCom_Core_Shell_DataIo
                        - FCom_Core_Shell_Help
                        - FCom_Core_Shell_Migrate
                        - FCom_Core_Shell_Module
                observe:
                    - [ "FCom_Core_ImportExport::beforeImport", "FCom_Core_Shell_DataIo.onBeforeImport" ]
                    - [ "FCom_Core_ImportExport::import:beforeModel", "FCom_Core_Shell_DataIo.onBeforeModel" ]
                    - [ "FCom_Core_ImportExport::_importBatch:afterBatch", "FCom_Core_Shell_DataIo.onAfterBatch" ]

            FCom_Install:
                custom:
                    actions:
                        - FCom_Shell_Action_Help

        default_config:
            core:
                cache:
                    memcache:
                        host: localhost
                        port: 11211
            db:
                dbname: sellvana
                username: root
                logging: true
                implicit_migration: true
            web:
                csrf_check_method: token
                headers:
                    X-UA-Compatible: IE=edge
                    X-Frame-Options: SAMEORIGIN
                    X-XSS-Protection: 1
                    X-Content-Type-Options: nosniff
            cookie:
                session_check_ip: 1
                use_strict_mode: 1

            modules:
                FCom_Core:
                    company_name: Sellvana
                    site_title: Sellvana
                    copyright_message: Sellvana
                    admin_email: admin@example.com
                    support_name: Support
                    support_email: support@example.com
                    sales_name: Sales
                    sales_email: support@example.com
                    default_tz: "America/New_York"
                    default_country: US
                    base_locale: en_US
                    base_currency: USD
                    default_currency: USD
                    import_export:
                        batch_size: 1000
                        delete_after_import: 0
