modules:
    FCom_Core:
        version: 0.1.8
        channel: beta
        before_bootstrap: { callback: "FCom_Core_Main::beforeBootstrap" }
        run_level: REQUIRED
        description: "Base Sellvana classes and JS libraries"
        load_after: [ FCom_LibTwig ]
        auto_use: [ layout, views ]
        override:
            class:
                - [ BDbModule, FCom_Core_Model_Module ]
        views:
            - [ head, { view_class: FCom_Core_View_Head } ]
            - [ core/messages, { view_class: FCom_Core_View_Messages } ]
            - [ bottom_scripts, { view_class: FCom_Core_View_Head } ]
            - [ core/htmlgrid, { view_class: FCom_Core_View_HtmlGrid } ]
            - [ core/form-elements, { view_class: FCom_Core_View_FormElements } ]
            - [ core/backgrid, { view_class: FCom_Core_View_Backgrid } ]
            - [ core/slickgrid, { view_class: FCom_Core_View_Slickgrid } ]
            - [ core/simplegrid, { view_class: FCom_Core_View_SimpleGrid } ]
            - [ core/backbonegrid, { view_class: FCom_Core_View_BackboneGrid } ]
            - [ core/medialib, {view_class: FCom_Core_View_Abstract } ]
            - [ core/attachmentgrid, {view_class: FCom_Core_View_Abstract } ]

        observe:
            - [ "FCom_LibTwig_Main::init", FCom_Core_Main.onTwigInit ]

        default_config:
            db:
                dbname: sellvana
                username: root
                logging: true
                implicit_migration: true
            web:
                csrf_check_method: token
                headers:
                    X-UA-Compatible: IE=edge
                    X-Frame-Options: SAMEORIGIN
            cookie:
                session_check_ip: 1

            modules:
                FCom_Core:
                    company_name: Sellvana
                    site_title: Sellvana
                    copyright_message: Sellvana
                    admin_email: admin@example.com
                    support_name: Support
                    support_email: support@example.com
                    sales_name: Sales
                    sales_email: support@example.com
                    default_tz: "America/New_York"
                    default_country: US
                    import_export:
                        batch_size: 10
                        delete_after_import: 1
